const typeCars = [
    {
        id: 1,
        tipo: 'Deportivo',
        imagen: '/assets/Types/Type-Coupe-Sports.jpg',
    },
    {
        id: 2,
        tipo: 'Convertible',
        imagen: '/assets/Types/Type-Convertible.jpg',
    },
    {
        id: 3,
        tipo: 'Sedan',
        imagen: '/assets/Types/Type-Sedan-4-Door.jpg',
    },
    {
        id: 4,
        tipo: 'Eléctrico',
        imagen: '/assets/Types/Type-EV.png',
    },
    {
        id: 5,
        tipo: 'Supercar',
        imagen: '/assets/Types/Type-Supercar.jpg',
    },
    {
        id: 6,
        tipo: 'SUV',
        imagen: '/assets/Types/Type-SUV.png',
    },
    {
        id: 7,
        tipo: 'Ultra Luxury',
        imagen: '/assets/Types/Type-Ultra-Luxury.jpg',
    },
];

if(localStorage.getItem("typeCars") === null) {
    localStorage.setItem("typeCars", JSON.stringify(typeCars));
}

const brandsStart = [
    {
        id: 1,
        marca: 'Alfa Romeo',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Alfa-Romeo.png',
        logoTipo: '/assets/Brands/logotipo-Alfa-Romeo.png',
        imagoTipo: '/assets/Brands/imagotipo-Alfa-Romeo.png',
    },
    {
        id: 2,
        marca: 'Aston Martin',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-Aston-Martin.png',
        logoTipo: '/assets/Brands/logotipo-Aston-Martin.png',
        imagoTipo: '/assets/Brands/imagotipo-Aston-Martin.png',
    },
    {
        id: 3,
        marca: 'Audi',
        sede: 'Alemania',
        isoTipo: '/assets/Brands/isotipo-Audi.png',
        logoTipo: '/assets/Brands/logotipo-Audi.png',
        imagoTipo: '/assets/Brands/imagotipo-Audi.png',
    },
    {
        id: 4,
        marca: 'Bentley',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-BMW.png',
        logoTipo: '/assets/Brands/logotipo-BMW.png',
        imagoTipo: '/assets/Brands/imagotipo-BMW.png',
    },
    {
        id: 5,
        marca: 'BMW',
        sede: 'Alemania',
        isoTipo: '/assets/Brands/isotipo-BMW.png',
        logoTipo: '/assets/Brands/logotipo-BMW.png',
        imagoTipo: '/assets/Brands/imagotipo-BMW.png',
    },
    {
        id: 6,
        marca: 'Bugatti',
        sede: 'Francia',
        isoTipo: '/assets/Brands/isotipo-Bugatti.png',
        logoTipo: '/assets/Brands/logotipo-Bugatti.png',
        imagoTipo: '/assets/Brands/imagotipo-Bugatti.png',
    },
    {
        id: 7,
        marca: 'Ferrari',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Ferrari.png',
        logoTipo: '/assets/Brands/logotipo-Ferrari.png',
        imagoTipo: '/assets/Brands/imagotipo-Ferrari.png',
    },
    {
        id: 8,
        marca: 'Jaguar',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-Jaguar.png',
        logoTipo: '/assets/Brands/logotipo-Jaguar.png',
        imagoTipo: '/assets/Brands/imagotipo-Jaguar.png',
    },
    {
        id: 9,
        marca: 'Koenigsegg',
        sede: 'Suecia',
        isoTipo: '/assets/Brands/isotipo-Koenigsegg.png',
        logoTipo: '/assets/Brands/logotipo-Koenigsegg.png',
        imagoTipo: '/assets/Brands/imagotipo-Koenigsegg.png',
    },
    {
        id: 10,
        marca: 'Lamborghini',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Lamborghini.png',
        logoTipo: '/assets/Brands/logotipo-Lamborghini.png',
        imagoTipo: '/assets/Brands/imagotipo-Lamborghini.png',
    },
    {
        id: 11,
        marca: 'Maserati',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Maserati.png',
        logoTipo: '/assets/Brands/logotipo-Maserati.png',
        imagoTipo: '/assets/Brands/imagotipo-Maserati.png',
    },
    {
        id: 12,
        marca: 'McLaren',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-McLaren.png',
        logoTipo: '/assets/Brands/logotipo-McLaren.png',
        imagoTipo: '/assets/Brands/imagotipo-McLaren.png',
    },
    {
        id: 13,
        marca: 'Mercedes Benz',
        sede: 'Alemania',
        isoTipo: '/assets/Brands/isotipo-Mercedes-Benz.png',
        logoTipo: '/assets/Brands/logotipo-Mercedes-Benz.png',
        imagoTipo: '/assets/Brands/imagotipo-Mercedes-Benz.png',
    },
    {
        id: 14,
        marca: 'Pagani',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Pagani.png',
        logoTipo: '/assets/Brands/logotipo-Pagani.png',
        imagoTipo: '/assets/Brands/imagotipo-Pagani.png',
    },
    {
        id: 15,
        marca: 'Porsche',
        sede: 'Alemania',
        isoTipo: '/assets/Brands/isotipo-Porsche.png',
        logoTipo: '/assets/Brands/logotipo-Porsche.png',
        imagoTipo: '/assets/Brands/imagotipo-Porsche.png',
    },
    {
        id: 16,
        marca: 'Rolls Royce',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-Porsche.png',
        logoTipo: '/assets/Brands/logotipo-Porsche.png',
        imagoTipo: '/assets/Brands/imagotipo-Porsche.png',
    },
    {
        id: 17,
        marca: 'Tesla',
        sede: 'Estados Unidos',
        isoTipo: '/assets/Brands/isotipo-Porsche.png',
        logoTipo: '/assets/Brands/logotipo-Porsche.png',
        imagoTipo: '/assets/Brands/imagotipo-Porsche.png',
    },
];

if(localStorage.getItem("brands") === null) {
    localStorage.setItem("brands", JSON.stringify(brandsStart));
}

const testimonialsStart = [
    {
        id: 1,
        testimonio: 'Llamé a The SuperCar Club - Car Rental a las 9:00 a. m. para preguntar sobre la disponibilidad del auto de mis sueños y me entregaron el Lamborghini a las 11:00 a. m. del mismo día. La transacción fue simple y fluida.',
        fecha: new Date('2023-06-09').getTime(),
        autor: 'Shawn H.',
    },
    {
        id: 2,
        testimonio: 'The SuperCar Club es una empresa increíble. Tenían el Lamborghini exacto que necesitábamos y estaba en perfectas condiciones. La empresa es muy hospitalaria y el proceso es sencillo. Nos explicaron todo con el coche e hicieron un recorrido extenso.',
        fecha: new Date('2022-09-14').getTime(),
        autor: 'Eugene S.',
    },
    {
        id: 3,
        testimonio: 'The SuperCar Club hizo un esfuerzo adicional por nuestra empresa (nunca mejor dicho). Fueron muy serviciales y la comunicación fue eficiente. Utilizamos el magnífico Rolls Royce Dawn para nuestro vídeo musical con gran éxito.',
        fecha: new Date('2022-03-04').getTime(),
        autor: 'Gianna C.',
    },
    {
        id: 4,
        testimonio: 'Si buscas coches de calidad y un buen servicio, no te equivocarás aquí. El mejor servicio de alquiler de coches en Perú, sin duda. Tercera vez que alquilo desde aquí, nunca me decepcionó.',
        fecha: new Date('2021-04-25').getTime(),
        autor: 'Ryan M.',
    },
    {
        id: 5,
        testimonio: 'La asistencia que recibí fue excelente. Alquilé un Mercedes S550 Cabriolet para el baile de graduación de mi hija y fueron muy serviciales. ¡Se los recomendaría a todos y los usaré nuevamente en el futuro!',
        fecha: new Date('2020-09-17').getTime(),
        autor: 'Cathy J.',
    },
];

if(localStorage.getItem("testimonials") === null){
    localStorage.setItem("testimonials", JSON.stringify(testimonialsStart));
}

const usersStart = [
    {
        firstName: 'Renzo Alessandro',
        lastName: 'Sucari Velasquez',
        age: 30,
        email: 'admin@admin.com',
        id: '1',
        active: true,
        password: 'admin',
        bornDate: new Date('1996-02-14').getTime(),
        location: 'San Francisco, CA',
        image: 'https://cdn-icons-png.flaticon.com/512/3177/3177440.png',
        role: 'ADMIN_ROLE'
    },
    {
        firstName: 'Joaquín Daniel',
        lastName: 'Ramírez García',
        age: 30,
        email: 'joaquin.ramirez@example.com',
        id: '2',
        active: true,
        password: 'password123',
        bornDate: new Date('1993-01-01').getTime(),
        location: 'New York, NY',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/7/71/Mk8iconyoshi.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Santiago Vicente',
        lastName: 'Vázquez Garrido',
        age: 25,
        email: 'santiago.vazquez@example.com',
        id: '3',
        active: false,
        password: 'password456',
        bornDate: new Date('1998-05-05').getTime(),
        location: 'Los Angeles, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/f/f5/Mk8icondaisy.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Lucía Paula',
        lastName: 'Castillo Fernández',
        age: 35,
        email: 'lucia.castillo@example.com',
        id: '4',
        active: true,
        password: 'password789',
        bornDate: new Date('1988-08-08').getTime(),
        location: 'Miami, FL',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/1/1d/Mk8icontoadette.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Roberto Carlos',
        lastName: 'González García',
        age: 40,
        email: 'roberto.gonzalez@example.com',
        id: '5',
        active: false,
        password: 'password101',
        bornDate: new Date('1983-04-10').getTime(),
        location: 'Chicago, IL',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/d/d1/Mk8iconrosalina.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Yolanda Laura',
        lastName: 'Martín Serrano',
        age: 28,
        email: 'yolanda.martin@example.com',
        id: '6',
        active: true,
        password: 'password202',
        bornDate: new Date('1995-02-15').getTime(),
        location: 'Houston, TX',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/5/59/Mk8iconpeach.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Diego Sergio',
        lastName: 'Rodríguez Martínez',
        age: 34,
        email: 'diego.rodríguez@example.com',
        id: '7',
        active: false,
        password: 'password303',
        bornDate: new Date('1989-07-07').getTime(),
        location: 'San Francisco, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/b/bf/Mk8iconmario.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Laura Patricia',
        lastName: 'Vázquez Iglesias',
        age: 22,
        email: 'laura.vazquez@example.com',
        id: '8',
        active: true,
        password: 'password404',
        bornDate: new Date('2001-11-11').getTime(),
        location: 'Boston, MA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/2/2d/Mk8icondk.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Carlos David',
        lastName: 'Santos Ortíz',
        age: 45,
        email: 'carlos.santos@example.com',
        id: '9',
        active: false,
        password: 'password505',
        bornDate: new Date('1978-12-19').getTime(),
        location: 'Dallas, TX',
        image: "https://m.media-amazon.com/images/I/81wNRtDaTXL.png",
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Lucía María',
        lastName: 'García Caño',
        age: 29,
        email: 'lucía.garcia@example.com',
        id: '10',
        active: true,
        password: 'password606',
        bornDate: new Date('1994-06-24').getTime(),
        location: 'San Diego, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/3/3a/Mk8iconkoopa.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Jaime Alfonso',
        lastName: 'Núñez Medina',
        age: 31,
        email: 'jaime.nunez@example.com',
        id: '11',
        active: false,
        password: 'password707',
        bornDate: new Date('1992-03-03').getTime(),
        location: 'Denver, CO',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/b/b7/Mk8iconbowser.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Santiago Iván',
        lastName: 'Álvarez Torres',
        age: 30,
        email: 'santiago.alvarez@example.com',
        id: '12',
        active: true,
        password: 'password123',
        bornDate: new Date('1993-01-01').getTime(),
        location: 'New York, NY',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/7/71/Mk8iconyoshi.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Ramón Pablo',
        lastName: 'Blanco Pérez',
        age: 25,
        email: 'ramon.blanco@example.com',
        id: '13',
        active: false,
        password: 'password456',
        bornDate: new Date('1998-05-05').getTime(),
        location: 'Los Angeles, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/f/f5/Mk8icondaisy.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'María Ignacio',
        lastName: 'Navarro Martín',
        age: 35,
        email: 'maria.navarro@example.com',
        id: '14',
        active: true,
        password: 'password789',
        bornDate: new Date('1988-08-08').getTime(),
        location: 'Miami, FL',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/1/1d/Mk8icontoadette.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Andrea Concepción',
        lastName: 'Blanco Muñoz',
        age: 40,
        email: 'andrea.blanco@example.com',
        id: '15',
        active: false,
        password: 'password101',
        bornDate: new Date('1983-04-10').getTime(),
        location: 'Chicago, IL',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/d/d1/Mk8iconrosalina.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Mercedes Paula',
        lastName: 'Guerrero Núñez',
        age: 28,
        email: 'mercedes.guerrero@example.com',
        id: '16',
        active: true,
        password: 'password202',
        bornDate: new Date('1995-02-15').getTime(),
        location: 'Houston, TX',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/5/59/Mk8iconpeach.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Rocío Alicia',
        lastName: 'Ramos Delgado',
        age: 34,
        email: 'rocio.ramos@example.com',
        id: '17',
        active: false,
        password: 'password303',
        bornDate: new Date('1989-07-07').getTime(),
        location: 'San Francisco, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/b/bf/Mk8iconmario.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Javier Joaquín',
        lastName: 'Ortega Ramírez',
        age: 22,
        email: 'javier.ortega@example.com',
        id: '18',
        active: true,
        password: 'password404',
        bornDate: new Date('2001-11-11').getTime(),
        location: 'Boston, MA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/2/2d/Mk8icondk.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Emilio Enrique',
        lastName: 'Iglesias Alonso',
        age: 45,
        email: 'emilio.iglesias@example.com',
        id: '19',
        active: false,
        password: 'password505',
        bornDate: new Date('1978-12-19').getTime(),
        location: 'Dallas, TX',
        image: "https://m.media-amazon.com/images/I/81wNRtDaTXL.png",
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Juan Gabriel',
        lastName: 'Alonso Delgado',
        age: 29,
        email: 'juan.alonso@example.com',
        id: '20',
        active: true,
        password: 'password606',
        bornDate: new Date('2015-12-04').getTime(),
        location: 'San Diego, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/3/3a/Mk8iconkoopa.png?width=325',
        role: 'CLIENT_ROLE'
    }
];

if(localStorage.getItem("users") === null) {
    localStorage.setItem("users", JSON.stringify(usersStart));
}

var precision = 10; // Un decimal

const modelCarsStart = [
    // <option value="0">Alfa Romeo</option>
    {
        id: '100',
        marca: brandsStart[0],
        modelo: 'Giulia',
        motor: '2.2L 160 CV',
        tipo: typeCars[2],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 269,
        horsepowerHP: 280,
        de0a60MPH: 5.1,
        anio: new Date('2020-01-02').getTime(),
        color: '#ef233c',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 896,
        autoImg: '/assets/Cars/Alfa-Romeo/Alfaromeo-Giulia.png',
        descripcion: 'Tras someterse a una completa renovación en 2020, el Giulia ya estaba disponible en numerosas tonalidades para su carrocería y con un sistema de info-entretenimiento llamado Alfa Connect 3D que incluye pantalla de 8,8 pulgadas con navegador y datos del tráfico en tiempo real, así como lo último en conectividad para smartphones. Además, los servicios telemáticos Alfa Connected Services y sus múltiples asistentes a la conducción le valieron en día el nivel 2 de conducción autónoma.',
        active: true,
    },
    {
        id: '101',
        marca: brandsStart[0],
        modelo: 'Stelvio',
        motor: '2.2L 160 CV',
        tipo: typeCars[5],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 283,
        horsepowerHP: 280,
        de0a60MPH: 3.6,
        anio: new Date('2023-01-02').getTime(),
        color: '#ef233c',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 978,
        autoImg: '/assets/Cars/Alfa-Romeo/Alfaromeo-Stelvio.png',
        descripcion: 'El Alfa Romeo Stelvio 2023 está disponible en ocho colores de carrocería: Rojo Alfa, Blanco Alfa, Negro Volcano, Perla Luna, Azul Misano, Gris Vesuvio, Rojo Etna y Gris Mate (solo en Competizione); tres tipos de llantas (de 17, 18 y 19 pulgadas) y seis niveles de acabado: Super, Sprint, Ti, Veloce, Competizione y desde este último semestre de 2023 también la famosa versión deportiva Alfa Romeo Stelvio Quadrifoglio, que además llega acompañada de una edición especial limitada Quadrifoglio 100º Anniversario limitada a solo 100 unidades -compartidas con el Giulia y ya totalmente agotadas- con detalles únicos en celebración de los 100 años del famoso trébol de cuatro hojas símbolo de la herencia deportiva de Alfa.',
        active: true,
    },
    {
        id: '103',
        marca: brandsStart[0],
        modelo: 'Tonale',
        motor: '1.5L 160 CV',
        tipo: typeCars[5],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 209,
        horsepowerHP: 160,
        de0a60MPH: 6.2,
        anio: new Date('2021-01-02').getTime(),
        color: '#ef233c',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 786,
        autoImg: '/assets/Cars/Alfa-Romeo/Alfaromeo-Tonale.png',
        descripcion: 'El diseño general no ha sufrido grandes variaciones respecto al del citado prototipo, pero sobre todo permanece invariable desde otoño de 2021, cuando conocimos el primer Tonale preserie. Conserva elementos como los bifaros, la calandra central o los pilotos led y el portón trasero liso. Los faros 3+3 son matriciales adaptativos Full-LED y están desarrollados con la colaboración de Marelli.',
        active: true,
    },
    // <option value="1">Aston Martin</option>
    {
        id: '200',
        marca: brandsStart[1],
        modelo: 'DB11',
        motor: '4.0L 510 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 322 ,
        horsepowerHP: 528,
        de0a60MPH: 3.9,
        anio: new Date('2023-01-02').getTime(),
        color: '#dee2e6',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 768,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-DB11.png',
        descripcion: 'El Aston Martin DB11 es el modelo medio de Aston Martin, un Gran Turismo de altas prestaciones, heredero del mítico Aston Martin DB9 que tantas alegrías le dio al fabricante británico. Se comercializa su primera generación, la cual salió al mercado en 2016. Comparte chasis con el Aston Martin DBS Superleggera, una versión más deportiva y exclusiva que emplea gran parte de los elementos de carrocería y otros componentes base. Se fabrica artesanalmente en la factoría de Gaydon, Inglaterra, al igual que el Vanquish, Rapide y el Vantage.',
        active: true,
    },
    {
        id: '201',
        marca: brandsStart[1],
        modelo: 'DBS Superleggera',
        motor: '5.2L 725 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 340,
        horsepowerHP: 715,
        de0a60MPH: 1.7,
        anio: new Date('2018-01-02').getTime(),
        color: '#dee2e6',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 865,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-DBS-SuperLeggera.png',
        descripcion: 'El Aston Martin DBS Superleggera es un superdeportivo lanzado en 2018 que en esencia es la versión más deportiva y exclusiva desarrollada sobre la base del Aston Martin DB11. A pesar de compartir con el DB11 chasis, elementos mecánicos y otros componentes, el DBS Superleggera ofrece una visión más deportiva y radical para distanciarse del carácter GT del Aston Martin DB11.',
        active: true,
    },
    {
        id: '202',
        marca: brandsStart[1],
        modelo: 'DBX',
        motor: '4.0L 550 CV',
        tipo: typeCars[5],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 310,
        horsepowerHP: 542,
        de0a60MPH: 3.3,
        anio: new Date('2020-01-02').getTime(),
        color: '#06d6a0',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 987,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-DBX.png',
        descripcion: 'El Aston Martin DBX es un SUV deportivo y de lujo, comercializado por Aston Martin desde 2020. El Aston Martin DBX se caracteriza por ofrecer la deportividad a la que nos tiene acostumbrados Aston Martin, en equilibrio con el alto nivel de calidad y confort de que siempre han hecho gala sus grandes turismos.',
        active: true,
    },
    {
        id: '203',
        marca: brandsStart[1],
        modelo: 'Valhalla',
        motor: 'V6 Twin-Turbo 1.000 CV',
        tipo: typeCars[4],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 330,
        horsepowerHP: 950,
        de0a60MPH: 2.5,
        anio: new Date('2021-01-02').getTime(),
        color: '#006d77',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 765,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-Valhalla.png',
        descripcion: 'El Aston Martin Valhalla es un superdeportivo híbrido enchufable de motor V6 central fabricado por Aston Martin y que rinde 1.000 CV de potencia máxima. Se trata de un coche conocido incialmente como proyecto AM-RB 003 dado su desarrollo en colaboración con Red Bull. La filosofía de este coche es la de ofrecer un planteamiento muy similar al del Aston Martin Valkyrie, pero a una escala inferior en tamaño, prestaciones y precio.',
        active: true,
    },
    {
        id: '204',
        marca: brandsStart[1],
        modelo: 'Vanquish',
        motor: 'V12 520 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 295,
        horsepowerHP: 513,
        de0a60MPH: 4.1,
        anio: new Date('2021-01-02').getTime(),
        color: '#d90429',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 768,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-Vanquish.png',
        descripcion: 'El Aston Martin Vanquish S es la máxima expresión en cuanto a vehículos GT del fabricante inglés. El Vanquish es un modelo con gran tradición dentro de la marca, y su última evolución no deja lugar a dudas: se trata de todo un Aston Martin. Su diseño no pasa desapercibido, pero mantiene la elegancia inherente a todo vehículo de la firma británica.',
        active: true,
    },
    {
        id: '205',
        marca: brandsStart[1],
        modelo: 'Vantage',
        motor: '4.0L V8 Biturbo 510 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 314,
        horsepowerHP: 528,
        de0a60MPH: 3.5,
        anio: new Date('2021-01-02').getTime(),
        color: '#eeef20',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 876,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-Vantage.png',
        descripcion: 'El Aston Martin Vantage es un deportivo biplaza del fabricante británico Aston Martin, comercializado desde 2005. Actualmente se fabrica la segunda generación, presentada en 2017. El Aston Martin Vantage se caracteriza por ser el hermano pequeño del Aston Martin DB11 y presume de un reparto de pesos perfecto, un chasis ligero y un motor V8 Biturbo de origen Mercedes-AMG de 510 CV. Se fabrica en la planta de Aston Martin en Gaydon, Reino Unido.',
        active: true,
    },
    // <option value="2">Audi</option>
    {
        id: '300',
        marca: brandsStart[2],
        modelo: 'A6',
        motor: '2.0L 204 CV',
        tipo: typeCars[2],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 230,
        horsepowerHP: 335,
        de0a60MPH: 4.8,
        anio: new Date('2021-01-02').getTime(),
        color: '#ced4da',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 987,
        autoImg: '/assets/Cars/Audi/Audi-A6.png',
        descripcion: 'El Audi A6 es una berlina premium, del segmento E, fabricada por la marca Audi desde 1995. Se trata del sucesor del Audi 100. Actualmente se comercializa la tercera generación, presentada en 2018. El Audi A6 se caracteriza por sus casi 5 metros de longitud, es un coche de estética muy clásica pero tecnología de última generación, que está construido con el máximo cuidado en la calidad de cada detalle.',
        active: true,
    },
    {
        id: '301',
        marca: brandsStart[2],
        modelo: 'Q8 Sportback e-tron',
        motor: 'Eléctrico',
        tipo: typeCars[3],
        transmision: 'Automático',
        combustible: 'Eléctrico',
        velocidadMax: 250,
        horsepowerHP: 335,
        de0a60MPH: 6.0,
        anio: new Date('2022-01-02').getTime(),
        color: '#edf2f4',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 998,
        autoImg: '/assets/Cars/Audi/Audi-Q8-Sportback-e-tron.png',
        descripcion: 'El Audi Q8 es un SUV coupé, del segmento E, fabricado por Audi desde 2018. Actualmente se comercializa la primera generación. El Audi Q8 destaca por ofrecer una visión más deportiva y exclusiva del todocamino según Audi. Se fabrica en la planta de Audi en Bratislava, Eslovaquia.',
        active: true,
    },
    {
        id: '302',
        marca: brandsStart[2],
        modelo: 'RS e-tron GT',
        motor: 'Eléctrico',
        tipo: typeCars[3],
        transmision: 'Automático',
        combustible: 'Eléctrico',
        velocidadMax: 250,
        horsepowerHP: 522,
        de0a60MPH: 3.3,
        anio: new Date('2023-01-02').getTime(),
        color: '#edf2f4',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 667,
        autoImg: '/assets/Cars/Audi/Audi-Q8-Sportback-e-tron.png',
        descripcion: 'El Audi Q8 es un SUV coupé, del segmento E, fabricado por Audi desde 2018. Actualmente se comercializa la primera generación. El Audi Q8 destaca por ofrecer una visión más deportiva y exclusiva del todocamino según Audi. Se fabrica en la planta de Audi en Bratislava, Eslovaquia.',
        active: true,
    },
    // <option value="3">Bentley</option>
    {
        id: '400',
        marca: brandsStart[3],
        modelo: 'Bentayga',
        motor: '3.0L 449CV',
        tipo: typeCars[6],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 306,
        horsepowerHP: 443,
        de0a60MPH: 3.6,
        anio: new Date('2023-01-02').getTime(),
        color: '#c0c0c0',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 989,
        autoImg: '/assets/Cars/Bentley/Bentley-Bentayga.png',
        descripcion: 'El Bentley Bentayga es un SUV de lujo, derivado del segmento F, fabricado por Bentley desde 2015. Actualmente se comercializa la primera generación, aunque actualizada en Junio 2020 a través de un restyling. El Bentayga se caracteriza por ofrecer una imagen de lujo y exclusividad al más alto nivel en sucategoría, añadiendo además un carácter con ciertos tines deportivos como sucede en todos los modelos de la marca.',
        active: true,
    },

    {
        id: '401',
        marca: brandsStart[3],
        modelo: 'Continental GT',
        motor: '6.0L W12 659CV',
        tipo: typeCars[6],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 335,
        horsepowerHP: 650,
        de0a60MPH: 3.5,
        anio: new Date('2022-01-02').getTime(),
        color: '#1976d2',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 989,
        autoImg: '/assets/Cars/Bentley/Bentley-Continental.png',
        descripcion: 'El Bentley Continental GT es el modelo más deportivo que comercializa la firma británica Bentley. Se trata de un coupé en configuración 2+2 plazas que se caracteriza por ofrecer un concepto donde priman el máximo lujo y las más altas prestaciones.',
        active: true,
    },
    // <option value="4">BMW</option>
    {
        id: '500',
        marca: brandsStart[4],
        modelo: 'i4',
        motor: 'Eléctrico',
        tipo: typeCars[2],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 223,
        horsepowerHP: 335,
        de0a60MPH: 5.8,
        anio: new Date('2023-01-02').getTime(),
        color: '#1f487e',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 564,
        autoImg: '/assets/Cars/BMW/BMW-i4.png',
        descripcion: 'El BMW i4 es una berlina eléctrica, del segmento D, que fabrica BMW desde el año 2022. El BMW i4 se caracteriza por ser algo así como la versión eléctrica del BMW Serie 4 Gran Coupé, con quien comparte las líneas generales de su diseño. A nivel técnico, cuenta con una autonomía WLTP de 590 km y hasta 544 CV de potencia en su versión más prestacional.',
        active: true,
    },
    // <option value="5">Bugatti</option>
    {
        id: '600',
        marca: brandsStart[5],
        modelo: 'Chiron',
        motor: '8.0L W16 1500CV',
        tipo: typeCars[4],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 490,
        horsepowerHP: 1600,
        de0a60MPH: 2.3,
        anio: new Date('2023-01-02').getTime(),
        color: '#0e6ba8',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 3289,
        autoImg: '/assets/Cars/Bugatti/Bugatti-Chiron.png',
        descripcion: 'El Bugatti Chiron es un hiperdeportivo de Bugatti, que reemplazó al Bugatti Veyron en 2016. El Bugatti Chiron se caracteriza por ser el vehículo más rápido del mundo, siendo capaz de sobrepasar los 490 kilómetros por hora.',
        active: true,
    },
    // <option value="6">Ferrari</option>
    {
        id: '700',
        marca: brandsStart[6],
        modelo: '812',
        motor: 'V12 800CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 345,
        horsepowerHP: 789,
        de0a60MPH: 2.8,
        anio: new Date('2021-01-02').getTime(),
        color: '#da4167',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 879,
        autoImg: '/assets/Cars/Ferrari/Ferrari-812.png',
        descripcion: 'El Ferrari 812 GTS es un superdeportivo descapotable de 800 CV, fabricado por Ferrari desde 2019. Está basado en el Ferrari 812 Superfast, con carrocería coupé, que se comercializó hasta entonces. Los Ferrari 812 son los Ferrari de serie más potentes de la historia y representan el tope de gama de la marca.',
        active: true,
    },
    // <option value="7">Jaguar</option>
    {
        id: '800',
        marca: brandsStart[7],
        modelo: 'F-Type',
        motor: '5.0L V8 575CV',
        tipo: typeCars[6],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 300,
        horsepowerHP: 575,
        de0a60MPH: 3.5,
        anio: new Date('2019-01-02').getTime(),
        color: '#e6e6e9',
        asientos: 987,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 968,
        autoImg: '/assets/Cars/Jaguar/Jaguar-F-Type.png',
        descripcion: 'El Jaguar F-Type es un deportivo biplaza, fabricado por Jaguar desde 2013. Actualmente se comercializa la primera generación, que fue actualizada a finales de 2019. Es considerado el heredero espiritual del icónico Jaguar E-Type, uno de los mejores clásicos de la marca.',
        active: true,
    },
    // <option value="8">Koenigsegg</option>
    {
        id: '900',
        marca: brandsStart[8],
        modelo: 'Agera RS',
        motor: '5.0L V8 1360CV',
        tipo: typeCars[4],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 444,
        horsepowerHP: 1160,
        de0a60MPH: 2.8,
        anio: new Date('2022-01-02').getTime(),
        color: '#212529',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 1265,
        autoImg: '/assets/Cars/Koenigsegg/Koenigsegg-Agera-RS.png',
        descripcion: 'Partes de la prueba: La historia de Koenigsegg y de Christian Koenigsegg Prestaciones del Koenigsegg Agera El Koenigsegg Agera en circuito Visita a la fábrica de Koenigsegg Galería de fotos Galería de fotos de la fábrica de Koenigsegg El Koenigsegg Agera es un superdeportivo biplaza sueco capaz de alcanzar en su versión más potente 1.155 caballos.',
        active: true,
    },
    // <option value="9">Lamborghini</option>
    {
        id: '1000',
        marca: brandsStart[9],
        modelo: 'Gallardo',
        motor: '5.2L V10 560CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 325,
        horsepowerHP: 493,
        de0a60MPH: 4.4,
        anio: new Date('2018-01-02').getTime(),
        color: '#212529',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 645,
        autoImg: '/assets/Cars/Lamborghini/Lamborghini-Gallardo.png',
        descripcion: 'El Lamborghini Gallardo es el modelo más accesible de la marca italiana Lamborghini. Está disponible con dos tipos de carrocería; Coupé y Roadster. Entre los rivales de este deportivo italiano, se encuentran el Audi R8, Porsche 911 o Ferrari 458 Italia.',
        active: true,
    },
    // <option value="10">Maserati</option>
    {
        id: '1100',
        marca: brandsStart[10],
        modelo: 'GranTurismo',
        motor: '4.7L V6 550 CV',
        tipo: typeCars[6],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 320,
        horsepowerHP: 454,
        de0a60MPH: 3.5,
        anio: new Date('2023-01-02').getTime(),
        color: '#ff0000',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 938,
        autoImg: '/assets/Cars/Maserati/Maserati-GranTurismo.png',
        descripcion: 'El Maserati GranTurismo es un superdeportivo fabricado por Maserati desde el año 2007. Actualmente se comercializa la segunda generación, lanzada al mercado en 2022. El Maserati GranTurismo se caracteriza por ofrecer una de las visiones más exactas del concepto de GT, de ahí su nombre, combinando deportividad, elegancia y lujo en un coche capaz de brindar por igual altas prestaciones o lujo.',
        active: true,
    },
    // <option value="11">McLaren</option>
    {
        id: '1200',
        marca: brandsStart[11],
        modelo: '570S',
        motor: '3.8L V8 Twin-Turbo 570 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 328,
        horsepowerHP: 562,
        de0a60MPH: 3.1,
        anio: new Date('2021-01-02').getTime(),
        color: '#fb8500',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 931,
        autoImg: '/assets/Cars/McLaren/McLaren-570S.png',
        descripcion: 'Los McLaren 570 forman parte de la gama Sport Series del constructor británico y quedan por debajo del McLaren 720S. Aunque tal y como sucede en todos los modelos McLaren, comparten diferentes elementos estructurales, piezas y la base del propulsor. Los McLaren 570 defienden el planteamiento menos radical de la gama, dando vida a la idea de deportivo capaz de conciliar el uso diario.',
        active: true,
    },
    // <option value="12">Mercedes Benz</option>
    {
        id: '1300',
        marca: brandsStart[12],
        modelo: 'AMG GT',
        motor: '4.0L V8 Twin-Turbo 730 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 315,
        horsepowerHP: 523,
        de0a60MPH:  3.2,
        anio: new Date('2021-01-02').getTime(),
        color: '#dee2e6',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 789,
        autoImg: '/assets/Cars/Mercedes-Benz/Mercedes-Benz-AMG-GT.png',
        descripcion: 'El Mercedes-AMG GT es un superdeportivo fabricado por Mercedes-Benz desde 2015. Actualmente se comercializa la segunda generación, presentada en 2023. El Mercedes-AMG GT se caracteriza por ofrecer grandes dosis de prestaciones y deportividad en un formato, el de coupé biplaza o 2+2, poco común en el mercado.',
        active: true,
    },
    // <option value="13">Pagani</option>
    {
        id: '1400',
        marca: brandsStart[13],
        modelo: 'Zonda',
        motor: '6.0L V12 750 CV',
        tipo: typeCars[4],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 400,
        horsepowerHP: 750,
        de0a60MPH: 3.2,
        anio: new Date('2021-01-02').getTime(),
        color: '#f1faee',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 1130,
        autoImg: '/assets/Cars/Pagani/Pagani-Zonda.png',
        descripcion: 'Se trata de la versión más extrema del Zonda, diseñado únicamente para circuito y con una producción limitada a 10 unidades que costarán 1,4 millones de euros.',
        active: true,
    },
    // <option value="14">Porsche</option>
    {
        id: '1500',
        marca: brandsStart[14],
        modelo: '718 Cayman GT4 RS',
        motor: '4.0L 500CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 315,
        horsepowerHP: 500,
        de0a60MPH: 3.4,
        anio: new Date('2021-01-02').getTime(),
        color: '#8d99ae',
        asientos: 2,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 783,
        autoImg: '/assets/Cars/Porsche/Porsche-718-Cayman-GT4-RS.png',
        descripcion: '23,6 segundos es el tiempo que el nuevo GT4 RS le ha metido a su hermano GT4 en Nürburgring. Eso hace ya una idea de cómo se las gasta la nueva criatura de Porsche. Un auténtico bólido que acelera de 0 a 100 en 3,4 segundos y logra una punta de 315 kilómetros/hora.',
        active: true,
    },
    // <option value="15">Rolls Royce</option>
    {
        id: '1600',
        marca: brandsStart[15],
        modelo: 'Cullinan',
        motor: '6.75 V12 Twin-Turbo de 571 CV',
        tipo: typeCars[5],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 250,
        horsepowerHP: 571,
        de0a60MPH: 5.2,
        anio: new Date('2021-01-02').getTime(),
        color: '#212529',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 2313,
        autoImg: '/assets/Cars/Rolls-Royce/RollsRoyce-Cullinan.png',
        descripcion: 'El Rolls-Royce Cullinan es el primer SUV fabricado por Rolls-Royce. Se trata de uno de los modelos más importantes jamás fabricado en su historia, modelo que además se convierte en un punto de inflexión tanto a nivel de ventas, como en la filosofía de producto de la marca por todo cuanto representa. Se trata del primer Rolls-Royce pensado para el uso fuera de asfalto, sin olvidar el lujo o la exclusividad.',
        active: true,
    },
    // <option value="16">Tesla</option>
    {
        id: '1700',
        marca: brandsStart[16],
        modelo: 'Model S',
        motor: '422 CV',
        tipo: typeCars[3],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 321,
        horsepowerHP: 422,
        de0a60MPH: 2.4,
        anio: new Date('2021-01-02').getTime(),
        color: '#e9ecef',
        asientos: 7,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 936,
        autoImg: '/assets/Cars/Tesla/Tesla-Model-S.png',
        descripcion: 'El Tesla Model S es una berlina eléctrica, del segmento E, fabricada por Tesla desde 2012. Aunque se trata de un producto veterano, ha sufrido ligeras actualizaciones con el paso de los años. El Tesla Model S tiene cinco plazas distribuidas en dos filas de asientos, pero opcionalmente se puede equipar con siete plazas gracias a una tercera fila con dos asientos para niños.',
        active: true,
    },
];

if(localStorage.getItem("modelCars") === null){
    console.log(modelCarsStart);
    localStorage.setItem("modelCars", JSON.stringify(modelCarsStart));
}
