const typeCars = [
    {
        id: 1,
        tipo: 'Deportivo',
        imagen: '/assets/Types/Type-Coupe-Sports.jpg',
    },
    {
        id: 2,
        tipo: 'Convertible',
        imagen: '/assets/Types/Type-Convertible.jpg',
    },
    {
        id: 3,
        tipo: 'Sedan',
        imagen: '/assets/Types/Type-Sedan-4-Door.jpg',
    },
    {
        id: 4,
        tipo: 'Eléctrico',
        imagen: '/assets/Types/Type-EV.png',
    },
    {
        id: 5,
        tipo: 'Supercar',
        imagen: '/assets/Types/Type-Supercar.jpg',
    },
    {
        id: 6,
        tipo: 'SUV',
        imagen: '/assets/Types/Type-SUV.png',
    },
    {
        id: 7,
        tipo: 'Ultra Luxury',
        imagen: '/assets/Types/Type-Ultra-Luxury.jpg',
    },
];

if(localStorage.getItem("typeCars") === null) {
    localStorage.setItem("typeCars", JSON.stringify(typeCars));
}

const brandsStart = [
    {
        id: 1,
        marca: 'Alfa Romeo',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Alfa-Romeo.png',
        logoTipo: '/assets/Brands/logotipo-Alfa-Romeo.png',
        imagoTipo: '/assets/Brands/imagotipo-Alfa-Romeo.png',
    },
    {
        id: 2,
        marca: 'Aston Martin',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-Aston-Martin.png',
        logoTipo: '/assets/Brands/logotipo-Aston-Martin.png',
        imagoTipo: '/assets/Brands/imagotipo-Aston-Martin.png',
    },
    {
        id: 3,
        marca: 'Audi',
        sede: 'Alemania',
        isoTipo: '/assets/Brands/isotipo-Audi.png',
        logoTipo: '/assets/Brands/logotipo-Audi.png',
        imagoTipo: '/assets/Brands/imagotipo-Audi.png',
    },
    {
        id: 4,
        marca: 'Bentley',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-BMW.png',
        logoTipo: '/assets/Brands/logotipo-BMW.png',
        imagoTipo: '/assets/Brands/imagotipo-BMW.png',
    },
    {
        id: 5,
        marca: 'BMW',
        sede: 'Alemania',
        isoTipo: '/assets/Brands/isotipo-BMW.png',
        logoTipo: '/assets/Brands/logotipo-BMW.png',
        imagoTipo: '/assets/Brands/imagotipo-BMW.png',
    },
    {
        id: 6,
        marca: 'Bugatti',
        sede: 'Francia',
        isoTipo: '/assets/Brands/isotipo-Bugatti.png',
        logoTipo: '/assets/Brands/logotipo-Bugatti.png',
        imagoTipo: '/assets/Brands/imagotipo-Bugatti.png',
    },
    {
        id: 7,
        marca: 'Ferrari',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Ferrari.png',
        logoTipo: '/assets/Brands/logotipo-Ferrari.png',
        imagoTipo: '/assets/Brands/imagotipo-Ferrari.png',
    },
    {
        id: 8,
        marca: 'Jaguar',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-Jaguar.png',
        logoTipo: '/assets/Brands/logotipo-Jaguar.png',
        imagoTipo: '/assets/Brands/imagotipo-Jaguar.png',
    },
    {
        id: 9,
        marca: 'Koenigsegg',
        sede: 'Suecia',
        isoTipo: '/assets/Brands/isotipo-Koenigsegg.png',
        logoTipo: '/assets/Brands/logotipo-Koenigsegg.png',
        imagoTipo: '/assets/Brands/imagotipo-Koenigsegg.png',
    },
    {
        id: 10,
        marca: 'Lamborghini',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Lamborghini.png',
        logoTipo: '/assets/Brands/logotipo-Lamborghini.png',
        imagoTipo: '/assets/Brands/imagotipo-Lamborghini.png',
    },
    {
        id: 11,
        marca: 'Maserati',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Maserati.png',
        logoTipo: '/assets/Brands/logotipo-Maserati.png',
        imagoTipo: '/assets/Brands/imagotipo-Maserati.png',
    },
    {
        id: 12,
        marca: 'McLaren',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-McLaren.png',
        logoTipo: '/assets/Brands/logotipo-McLaren.png',
        imagoTipo: '/assets/Brands/imagotipo-McLaren.png',
    },
    {
        id: 13,
        marca: 'Mercedes Benz',
        sede: 'Alemania',
        isoTipo: '/assets/Brands/isotipo-Mercedes-Benz.png',
        logoTipo: '/assets/Brands/logotipo-Mercedes-Benz.png',
        imagoTipo: '/assets/Brands/imagotipo-Mercedes-Benz.png',
    },
    {
        id: 14,
        marca: 'Pagani',
        sede: 'Italia',
        isoTipo: '/assets/Brands/isotipo-Pagani.png',
        logoTipo: '/assets/Brands/logotipo-Pagani.png',
        imagoTipo: '/assets/Brands/imagotipo-Pagani.png',
    },
    {
        id: 15,
        marca: 'Porsche',
        sede: 'Alemania',
        isoTipo: '/assets/Brands/isotipo-Porsche.png',
        logoTipo: '/assets/Brands/logotipo-Porsche.png',
        imagoTipo: '/assets/Brands/imagotipo-Porsche.png',
    },
    {
        id: 16,
        marca: 'Rolls Royce',
        sede: 'Reino Unido',
        isoTipo: '/assets/Brands/isotipo-Porsche.png',
        logoTipo: '/assets/Brands/logotipo-Porsche.png',
        imagoTipo: '/assets/Brands/imagotipo-Porsche.png',
    },
    {
        id: 17,
        marca: 'Tesla',
        sede: 'Estados Unidos',
        isoTipo: '/assets/Brands/isotipo-Porsche.png',
        logoTipo: '/assets/Brands/logotipo-Porsche.png',
        imagoTipo: '/assets/Brands/imagotipo-Porsche.png',
    },
];

if(localStorage.getItem("brands") === null) {
    localStorage.setItem("brands", JSON.stringify(brandsStart));
}

const testimonialsStart = [
    {
        id: 1,
        testimonio: 'Llamé a The SuperCar Club - Car Rental a las 9:00 a. m. para preguntar sobre la disponibilidad del auto de mis sueños y me entregaron el Lamborghini a las 11:00 a. m. del mismo día. La transacción fue simple y fluida.',
        fecha: new Date('2023-06-09').getTime(),
        autor: 'Shawn H.',
    },
    {
        id: 2,
        testimonio: 'The SuperCar Club es una empresa increíble. Tenían el Lamborghini exacto que necesitábamos y estaba en perfectas condiciones. La empresa es muy hospitalaria y el proceso es sencillo. Nos explicaron todo con el coche e hicieron un recorrido extenso.',
        fecha: new Date('2022-09-14').getTime(),
        autor: 'Eugene S.',
    },
    {
        id: 3,
        testimonio: 'The SuperCar Club hizo un esfuerzo adicional por nuestra empresa (nunca mejor dicho). Fueron muy serviciales y la comunicación fue eficiente. Utilizamos el magnífico Rolls Royce Dawn para nuestro vídeo musical con gran éxito.',
        fecha: new Date('2022-03-04').getTime(),
        autor: 'Gianna C.',
    },
    {
        id: 4,
        testimonio: 'Si buscas coches de calidad y un buen servicio, no te equivocarás aquí. El mejor servicio de alquiler de coches en Perú, sin duda. Tercera vez que alquilo desde aquí, nunca me decepcionó.',
        fecha: new Date('2021-04-25').getTime(),
        autor: 'Ryan M.',
    },
    {
        id: 5,
        testimonio: 'La asistencia que recibí fue excelente. Alquilé un Mercedes S550 Cabriolet para el baile de graduación de mi hija y fueron muy serviciales. ¡Se los recomendaría a todos y los usaré nuevamente en el futuro!',
        fecha: new Date('2020-09-17').getTime(),
        autor: 'Cathy J.',
    },
];

if(localStorage.getItem("testimonials") === null){
    localStorage.setItem("testimonials", JSON.stringify(testimonialsStart));
}

const usersStart = [
    {
        firstName: 'Renzo Alessandro',
        lastName: 'Sucari Velasquez',
        age: 30,
        email: 'admin@admin.com',
        id: '1',
        active: true,
        password: 'admin',
        bornDate: new Date('1996-02-14').getTime(),
        location: 'San Francisco, CA',
        image: 'https://cdn-icons-png.flaticon.com/512/3177/3177440.png',
        role: 'ADMIN_ROLE'
    },
    {
        firstName: 'Joaquín Daniel',
        lastName: 'Ramírez García',
        age: 30,
        email: 'joaquin.ramirez@example.com',
        id: '2',
        active: true,
        password: 'password123',
        bornDate: new Date('1993-01-01').getTime(),
        location: 'New York, NY',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/7/71/Mk8iconyoshi.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Santiago Vicente',
        lastName: 'Vázquez Garrido',
        age: 25,
        email: 'santiago.vazquez@example.com',
        id: '3',
        active: false,
        password: 'password456',
        bornDate: new Date('1998-05-05').getTime(),
        location: 'Los Angeles, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/f/f5/Mk8icondaisy.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Lucía Paula',
        lastName: 'Castillo Fernández',
        age: 35,
        email: 'lucia.castillo@example.com',
        id: '4',
        active: true,
        password: 'password789',
        bornDate: new Date('1988-08-08').getTime(),
        location: 'Miami, FL',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/1/1d/Mk8icontoadette.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Roberto Carlos',
        lastName: 'González García',
        age: 40,
        email: 'roberto.gonzalez@example.com',
        id: '5',
        active: false,
        password: 'password101',
        bornDate: new Date('1983-04-10').getTime(),
        location: 'Chicago, IL',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/d/d1/Mk8iconrosalina.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Yolanda Laura',
        lastName: 'Martín Serrano',
        age: 28,
        email: 'yolanda.martin@example.com',
        id: '6',
        active: true,
        password: 'password202',
        bornDate: new Date('1995-02-15').getTime(),
        location: 'Houston, TX',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/5/59/Mk8iconpeach.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Diego Sergio',
        lastName: 'Rodríguez Martínez',
        age: 34,
        email: 'diego.rodríguez@example.com',
        id: '7',
        active: false,
        password: 'password303',
        bornDate: new Date('1989-07-07').getTime(),
        location: 'San Francisco, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/b/bf/Mk8iconmario.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Laura Patricia',
        lastName: 'Vázquez Iglesias',
        age: 22,
        email: 'laura.vazquez@example.com',
        id: '8',
        active: true,
        password: 'password404',
        bornDate: new Date('2001-11-11').getTime(),
        location: 'Boston, MA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/2/2d/Mk8icondk.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Carlos David',
        lastName: 'Santos Ortíz',
        age: 45,
        email: 'carlos.santos@example.com',
        id: '9',
        active: false,
        password: 'password505',
        bornDate: new Date('1978-12-19').getTime(),
        location: 'Dallas, TX',
        image: "https://m.media-amazon.com/images/I/81wNRtDaTXL.png",
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Lucía María',
        lastName: 'García Caño',
        age: 29,
        email: 'lucía.garcia@example.com',
        id: '10',
        active: true,
        password: 'password606',
        bornDate: new Date('1994-06-24').getTime(),
        location: 'San Diego, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/3/3a/Mk8iconkoopa.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Jaime Alfonso',
        lastName: 'Núñez Medina',
        age: 31,
        email: 'jaime.nunez@example.com',
        id: '11',
        active: false,
        password: 'password707',
        bornDate: new Date('1992-03-03').getTime(),
        location: 'Denver, CO',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/b/b7/Mk8iconbowser.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Santiago Iván',
        lastName: 'Álvarez Torres',
        age: 30,
        email: 'santiago.alvarez@example.com',
        id: '12',
        active: true,
        password: 'password123',
        bornDate: new Date('1993-01-01').getTime(),
        location: 'New York, NY',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/7/71/Mk8iconyoshi.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Ramón Pablo',
        lastName: 'Blanco Pérez',
        age: 25,
        email: 'ramon.blanco@example.com',
        id: '13',
        active: false,
        password: 'password456',
        bornDate: new Date('1998-05-05').getTime(),
        location: 'Los Angeles, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/f/f5/Mk8icondaisy.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'María Ignacio',
        lastName: 'Navarro Martín',
        age: 35,
        email: 'maria.navarro@example.com',
        id: '14',
        active: true,
        password: 'password789',
        bornDate: new Date('1988-08-08').getTime(),
        location: 'Miami, FL',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/1/1d/Mk8icontoadette.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Andrea Concepción',
        lastName: 'Blanco Muñoz',
        age: 40,
        email: 'andrea.blanco@example.com',
        id: '15',
        active: false,
        password: 'password101',
        bornDate: new Date('1983-04-10').getTime(),
        location: 'Chicago, IL',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/d/d1/Mk8iconrosalina.png?width=1280',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Mercedes Paula',
        lastName: 'Guerrero Núñez',
        age: 28,
        email: 'mercedes.guerrero@example.com',
        id: '16',
        active: true,
        password: 'password202',
        bornDate: new Date('1995-02-15').getTime(),
        location: 'Houston, TX',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/5/59/Mk8iconpeach.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Rocío Alicia',
        lastName: 'Ramos Delgado',
        age: 34,
        email: 'rocio.ramos@example.com',
        id: '17',
        active: false,
        password: 'password303',
        bornDate: new Date('1989-07-07').getTime(),
        location: 'San Francisco, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/b/bf/Mk8iconmario.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Javier Joaquín',
        lastName: 'Ortega Ramírez',
        age: 22,
        email: 'javier.ortega@example.com',
        id: '18',
        active: true,
        password: 'password404',
        bornDate: new Date('2001-11-11').getTime(),
        location: 'Boston, MA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/2/2d/Mk8icondk.png?width=325',
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Emilio Enrique',
        lastName: 'Iglesias Alonso',
        age: 45,
        email: 'emilio.iglesias@example.com',
        id: '19',
        active: false,
        password: 'password505',
        bornDate: new Date('1978-12-19').getTime(),
        location: 'Dallas, TX',
        image: "https://m.media-amazon.com/images/I/81wNRtDaTXL.png",
        role: 'CLIENT_ROLE'
    },
    {
        firstName: 'Juan Gabriel',
        lastName: 'Alonso Delgado',
        age: 29,
        email: 'juan.alonso@example.com',
        id: '20',
        active: true,
        password: 'password606',
        bornDate: new Date('2015-12-04').getTime(),
        location: 'San Diego, CA',
        image: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-for-wii-u/3/3a/Mk8iconkoopa.png?width=325',
        role: 'CLIENT_ROLE'
    }
];

if(localStorage.getItem("users") === null) {
    localStorage.setItem("users", JSON.stringify(usersStart));
}

var precision = 10; // Un decimal

const modelCarsStart = [
    // <option value="0">Alfa Romeo</option>
    {
        id: '1',
        marca: brandsStart[0],
        modelo: 'Giulia',
        motor: '2.2L 160 CV',
        tipo: typeCars[2],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 269,
        horsepowerHP: 280,
        de0a60MPH: 5.1,
        anio: new Date('2020-01-02').getTime(),
        color: '#ef233c',
        asientos: 4,
        ratingCount: Math.floor(Math.random() * (5 * precision - 0 * precision) + 0 * precision) / (1*precision),
        precio_24h: 896,
        autoImg: '/assets/Cars/Alfa-Romeo/Alfaromeo-Giulia.png',
        descripcion: 'Tras someterse a una completa renovación en 2020, el Giulia ya estaba disponible en numerosas tonalidades para su carrocería y con un sistema de info-entretenimiento llamado Alfa Connect 3D que incluye pantalla de 8,8 pulgadas con navegador y datos del tráfico en tiempo real, así como lo último en conectividad para smartphones. Además, los servicios telemáticos Alfa Connected Services y sus múltiples asistentes a la conducción le valieron en día el nivel 2 de conducción autónoma.',
        active: true,
    },
    {
        id: '2',
        marca: brandsStart[0],
        modelo: 'Stelvio',
        motor: '2.2L 160 CV',
        tipo: typeCars[5],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 283,
        horsepowerHP: 280,
        de0a60MPH: 3.6,
        anio: new Date('2023-01-02').getTime(),
        color: '#ef233c',
        asientos: 4,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 978,
        autoImg: '/assets/Cars/Alfa-Romeo/Alfaromeo-Stelvio.png',
        descripcion: 'El Alfa Romeo Stelvio 2023 está disponible en ocho colores de carrocería: Rojo Alfa, Blanco Alfa, Negro Volcano, Perla Luna, Azul Misano, Gris Vesuvio, Rojo Etna y Gris Mate (solo en Competizione); tres tipos de llantas (de 17, 18 y 19 pulgadas) y seis niveles de acabado: Super, Sprint, Ti, Veloce, Competizione y desde este último semestre de 2023 también la famosa versión deportiva Alfa Romeo Stelvio Quadrifoglio, que además llega acompañada de una edición especial limitada Quadrifoglio 100º Anniversario limitada a solo 100 unidades -compartidas con el Giulia y ya totalmente agotadas- con detalles únicos en celebración de los 100 años del famoso trébol de cuatro hojas símbolo de la herencia deportiva de Alfa.',
        active: true,
    },
    {
        id: '3',
        marca: brandsStart[0],
        modelo: 'Tonale',
        motor: '1.5L 160 CV',
        tipo: typeCars[5],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 209,
        horsepowerHP: 160,
        de0a60MPH: 6.2,
        anio: new Date('2021-01-02').getTime(),
        color: '#ef233c',
        asientos: 4,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 786,
        autoImg: '/assets/Cars/Alfa-Romeo/Alfaromeo-Tonale.png',
        descripcion: 'El diseño general no ha sufrido grandes variaciones respecto al del citado prototipo, pero sobre todo permanece invariable desde otoño de 2021, cuando conocimos el primer Tonale preserie. Conserva elementos como los bifaros, la calandra central o los pilotos led y el portón trasero liso. Los faros 3+3 son matriciales adaptativos Full-LED y están desarrollados con la colaboración de Marelli.',
        active: true,
    },
    // <option value="1">Aston Martin</option>
    {
        id: '4',
        marca: brandsStart[1],
        modelo: 'DB11',
        motor: '4.0L 510 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 322 ,
        horsepowerHP: 528,
        de0a60MPH: 3.9,
        anio: new Date('2023-01-02').getTime(),
        color: '#dee2e6',
        asientos: 4,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 768,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-DB11.png',
        descripcion: 'El Aston Martin DB11 es el modelo medio de Aston Martin, un Gran Turismo de altas prestaciones, heredero del mítico Aston Martin DB9 que tantas alegrías le dio al fabricante británico. Se comercializa su primera generación, la cual salió al mercado en 2016. Comparte chasis con el Aston Martin DBS Superleggera, una versión más deportiva y exclusiva que emplea gran parte de los elementos de carrocería y otros componentes base. Se fabrica artesanalmente en la factoría de Gaydon, Inglaterra, al igual que el Vanquish, Rapide y el Vantage.',
        active: true,
    },
    {
        id: '5',
        marca: brandsStart[1],
        modelo: 'DBS Superleggera',
        motor: '5.2L 725 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 340,
        horsepowerHP: 715,
        de0a60MPH: 1.7,
        anio: new Date('2018-01-02').getTime(),
        color: '#dee2e6',
        asientos: 2,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 865,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-DBS-SuperLeggera.png',
        descripcion: 'El Aston Martin DBS Superleggera es un superdeportivo lanzado en 2018 que en esencia es la versión más deportiva y exclusiva desarrollada sobre la base del Aston Martin DB11. A pesar de compartir con el DB11 chasis, elementos mecánicos y otros componentes, el DBS Superleggera ofrece una visión más deportiva y radical para distanciarse del carácter GT del Aston Martin DB11.',
        active: true,
    },
    {
        id: '6',
        marca: brandsStart[1],
        modelo: 'DBX',
        motor: '4.0L 550 CV',
        tipo: typeCars[5],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 310,
        horsepowerHP: 542,
        de0a60MPH: 3.3,
        anio: new Date('2020-01-02').getTime(),
        color: '#06d6a0',
        asientos: 2,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 987,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-DBX.png',
        descripcion: 'El Aston Martin DBX es un SUV deportivo y de lujo, comercializado por Aston Martin desde 2020. El Aston Martin DBX se caracteriza por ofrecer la deportividad a la que nos tiene acostumbrados Aston Martin, en equilibrio con el alto nivel de calidad y confort de que siempre han hecho gala sus grandes turismos.',
        active: true,
    },
    {
        id: '7',
        marca: brandsStart[1],
        modelo: 'Valhalla',
        motor: 'V6 Twin-Turbo 1.000 CV',
        tipo: typeCars[4],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 330,
        horsepowerHP: 950,
        de0a60MPH: 2.5,
        anio: new Date('2021-01-02').getTime(),
        color: '#006d77',
        asientos: 2,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 765,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-Valhalla.png',
        descripcion: 'El Aston Martin Valhalla es un superdeportivo híbrido enchufable de motor V6 central fabricado por Aston Martin y que rinde 1.000 CV de potencia máxima. Se trata de un coche conocido incialmente como proyecto AM-RB 003 dado su desarrollo en colaboración con Red Bull. La filosofía de este coche es la de ofrecer un planteamiento muy similar al del Aston Martin Valkyrie, pero a una escala inferior en tamaño, prestaciones y precio.',
        active: true,
    },
    {
        id: '8',
        marca: brandsStart[1],
        modelo: 'Vanquish',
        motor: 'V12 520 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 295,
        horsepowerHP: 513,
        de0a60MPH: 4.1,
        anio: new Date('2021-01-02').getTime(),
        color: '#d90429',
        asientos: 2,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 768,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-Vanquish.png',
        descripcion: 'El Aston Martin Vanquish S es la máxima expresión en cuanto a vehículos GT del fabricante inglés. El Vanquish es un modelo con gran tradición dentro de la marca, y su última evolución no deja lugar a dudas: se trata de todo un Aston Martin. Su diseño no pasa desapercibido, pero mantiene la elegancia inherente a todo vehículo de la firma británica.',
        active: true,
    },
    {
        id: '9',
        marca: brandsStart[1],
        modelo: 'Vantage',
        motor: '4.0L V8 Biturbo 510 CV',
        tipo: typeCars[0],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 314,
        horsepowerHP: 528,
        de0a60MPH: 3.5,
        anio: new Date('2021-01-02').getTime(),
        color: '#eeef20',
        asientos: 2,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 876,
        autoImg: '/assets/Cars/Aston-Martin/AstonMartin-Vantage.png',
        descripcion: 'El Aston Martin Vantage es un deportivo biplaza del fabricante británico Aston Martin, comercializado desde 2005. Actualmente se fabrica la segunda generación, presentada en 2017. El Aston Martin Vantage se caracteriza por ser el hermano pequeño del Aston Martin DB11 y presume de un reparto de pesos perfecto, un chasis ligero y un motor V8 Biturbo de origen Mercedes-AMG de 510 CV. Se fabrica en la planta de Aston Martin en Gaydon, Reino Unido.',
        active: true,
    },
    // <option value="2">Audi</option>
    {
        id: '10',
        marca: brandsStart[2],
        modelo: 'A6',
        motor: '2.0L 204 CV',
        tipo: typeCars[2],
        transmision: 'Automático',
        combustible: 'Gasolina',
        velocidadMax: 230,
        horsepowerHP: 335,
        de0a60MPH: 4.8,
        anio: new Date('2021-01-02').getTime(),
        color: '#ced4da',
        asientos: 4,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 987,
        autoImg: '/assets/Cars/Audi/Audi-A6.png',
        descripcion: 'El Audi A6 es una berlina premium, del segmento E, fabricada por la marca Audi desde 1995. Se trata del sucesor del Audi 100. Actualmente se comercializa la tercera generación, presentada en 2018. El Audi A6 se caracteriza por sus casi 5 metros de longitud, es un coche de estética muy clásica pero tecnología de última generación, que está construido con el máximo cuidado en la calidad de cada detalle.',
        active: true,
    },
    {
        id: '11',
        marca: brandsStart[2],
        modelo: 'Q8 Sportback e-tron',
        motor: 'Eléctrico',
        tipo: typeCars[3],
        transmision: 'Automático',
        combustible: 'Eléctrico',
        velocidadMax: 250,
        horsepowerHP: 335,
        de0a60MPH: 6.0,
        anio: new Date('2021-01-02').getTime(),
        color: '#edf2f4',
        asientos: 4,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 998,
        autoImg: '/assets/Cars/Audi/Audi-Q8-Sportback-e-tron.png',
        descripcion: 'El Audi Q8 es un SUV coupé, del segmento E, fabricado por Audi desde 2018. Actualmente se comercializa la primera generación. El Audi Q8 destaca por ofrecer una visión más deportiva y exclusiva del todocamino según Audi. Se fabrica en la planta de Audi en Bratislava, Eslovaquia.',
        active: true,
    },
    {
        id: '12',
        marca: brandsStart[2],
        modelo: 'RS e-tron GT',
        motor: 'Eléctrico',
        tipo: typeCars[3],
        transmision: 'Automático',
        combustible: 'Eléctrico',
        velocidadMax: 250,
        horsepowerHP: 522,
        de0a60MPH: 3.3,
        anio: new Date('2021-01-02').getTime(),
        color: '#edf2f4',
        asientos: 4,
        ratingCount: Math.random() * (5 - 0) + 0,
        precio_24h: 667,
        autoImg: '/assets/Cars/Audi/Audi-Q8-Sportback-e-tron.png',
        descripcion: 'El Audi Q8 es un SUV coupé, del segmento E, fabricado por Audi desde 2018. Actualmente se comercializa la primera generación. El Audi Q8 destaca por ofrecer una visión más deportiva y exclusiva del todocamino según Audi. Se fabrica en la planta de Audi en Bratislava, Eslovaquia.',
        active: true,
    },
    // <option value="3">Bentley</option>
    // <option value="4">BMW</option>
    // <option value="5">Bugatti</option>
    // <option value="6">Ferrari</option>
    // <option value="7">Jaguar</option>
    // <option value="8">Koenigsegg</option>
    // <option value="9">Lamborghini</option>
    // <option value="10">Maserati</option>
    // <option value="11">McLaren</option>
    // <option value="12">Mercedes Benz</option>
    // <option value="13">Pagani</option>
    // <option value="14">Porsche</option>
    // <option value="15">Rolls Royce</option>
    // <option value="16">Tesla</option>
];

if(localStorage.getItem("modelCars") === null){
    console.log(modelCarsStart);
    localStorage.setItem("modelCars", JSON.stringify(modelCarsStart));
}
